name: Checkov Security Scan

on:
  workflow_dispatch:

jobs:
  checkov:
    name: Checkov IaC Security Scan
    runs-on: ubuntu-latest

    steps:
      # ── 1. Checkout del repositorio ──────────────────────────
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # ── 2. Ejecutar Checkov ───────────────────────────────────
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@7b972723c44fb3d256283fac96fae5d7c1894bb7 # v12.3114.0
        with:
          directory: iac
          framework: terraform
          output_format: junitxml
          output_file_path: results.xml
          soft_fail: true
          
      - name: Checkov Resultados
        if: always()
        run: |
          echo "CHECKOV RESULTS"
          cat results.xml

      # ── 3. Publicar resultados en GitHub ──────────────────────
      - name: Publish Checkov Results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: checkov-results
          path: results.xml
          retention-days: 30
