name: Terraform Unlock

on:
  workflow_dispatch:

env:
  TF_VERSION: "1.9.0"
  AWS_REGION: "us-east-2"
  WORKING_DIR: "iac"

jobs:
  unlock:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        run: |
          curl -fsSL https://releases.hashicorp.com/terraform/${{ env.TF_VERSION }}/terraform_${{ env.TF_VERSION }}_linux_amd64.zip -o terraform.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/

      - name: Terraform Init
        run: terraform init -input=false

      - name: Force Unlock
        run: terraform force-unlock -force 197dcd1f-36c5-ddba-a5d6-af1e1dcf5d6f
