name: SonarQube Analysis

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  sonarqube:
    name: Análisis SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Analizar con SonarCloud
        uses: SonarSource/sonarcloud-github-action@49e6cd3b187936a73b8280d59be7e75d3f8cc639 # v3.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
