name: SonarQube Analysis



on:

  push:

    branches:

      - hotfix




jobs:

  sonarqube:

    name: Análisis SonarQube

    runs-on: ubuntu-latest

    steps:

      - name: Checkout del código

        uses: actions/checkout@v4

        with:

          fetch-depth: 0



      - name: Analizar con SonarQube

        uses: SonarSource/sonarqube-scan-action@master

        env:

          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}